[package]
name = "plumcast"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
atomic_immut = "0.1"
bytecodec = "0.4"
fibers = "0.1"
fibers_rpc = "*"
futures = "0.1"
hyparview = "*"
slog = "2"
plumtree = "*"
protobuf_codec = "*"
trackable = "0.2"
